norloc/urls.py
# Imports
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from productions import views as prd
from locations import views as loc


# URL patterns
urlpatterns = [
    url(r'^$', prd.index, name='index'),

    # url(r'^produksjoner/$', include([
    #     url(r'^$', prd.productions, name='productions')
    # ])),

    url(r'^produksjoner/$', prd.productions, name='productions'),
    url(r'^produksjoner/import/$', prd.import_production, name='import_production'),
    url(r'^produksjoner/import/(?P<production_type>film|tv)/(?P<tmdb_id>\d+)$', prd.import_production, name='import_production'),
    url(r'^produksjoner/(?P<filter>[\w-]+)/$', prd.productions, name='filtered_productions'),
    url(r'^produksjoner/(?P<production_type>film|tv)/(?P<slug>[\w-]+)/$', prd.production, name='production'),

    url(r'^folk/$', prd.people, name='people'),
    url(r'^folk/import/$', prd.import_person, name='import_person'),
    url(r'^folk/(?P<job_filter>[\w-]+)/$', prd.people, name='filtered_people'),
    url(r'^person/(?P<slug>[\w-]+)/$', prd.person, name='person'),
    
    url(r'^kart/$', prd.map, name='map'),

    url(r'^json/production/(?P<ppk>\d+)/locations/$', prd.locations, name='production_locations'),
    url(r'^json/shots/$', prd.shots, name='shots'),
    url(r'^json/scenes/$', prd.scenes, name='scenes'),
    url(r'^json/tags/people/$', prd.people_tags, name='people_tags'),
    url(r'^json/tags/companies/$', prd.companies_tags, name='companies_tags'),
    url(r'^json/tmdb/production/search/$', prd.tmdb_production_search, name='tmdb_production_search'),
    url(r'^json/tmdb/production/(?P<production_type>film|tv)/details/(?P<tmdb_id>\d+)$', prd.tmdb_production_details, name='tmdb_production_details'),
    url(r'^json/tmdb/people/search/$', prd.tmdb_people_search, name='tmdb_people_search'),
    url(r'^json/tmdb/people/details/(?P<tmdb_id>\d+)$', prd.tmdb_person_details, name='tmdb_person_details'),

    url(r'^opptakssteder/$', loc.locations, name='locations'),
    url(r'^opptakssteder/(?P<county>[\w-]+)/$', loc.locations, name='locations'),
    url(r'^opptakssteder/(?P<county>[\w-]+)/(?P<place>[\w-]+)/$', loc.locations, name='locations'),
    url(r'^opptakssteder/(?P<county>[\w-]+)/(?P<place>[\w-]+)/(?P<slug>[\w-]+)$', loc.location, name='location'),

    url(r'^json/location/(?P<lpk>\d+)/productions/$', loc.productions, name='location_productions'),

    url(r'^json/locations/$', loc.locations, {'json': 'True'}, name='json_locations'),

    url(r'^json/location/(?P<lpk>\d+)/details$', loc.location_details, name='location_details'),
    url(r'^json/location/(?P<lpk>\d+)/bounds/update$', loc.update_location_bounds, name='update_bounds'),
    # url(r'^json/locations/$', loc.locations, name='locations'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





'''
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns('',
    # Main
    url(r'^$', views.index),

    # Apps
    url(r'^productions/', include('productions.urls')),
    url(r'^locations/', include('locations.urls')),

    # Test
    url(r'^test/', TemplateView.as_view(template_name='test.html')),

    # Tooltips
    url(r'^tooltip/login', TemplateView.as_view(template_name='tooltip_login.html')),
    url(r'^tooltip/user', TemplateView.as_view(template_name='tooltip_user.html')),

    # Auth
    url(r'^login/', views.login),
    url(r'^logout/', views.logout),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Productions
    url(r'^$', views.index, name='productions'),
    url(r'^films/$', views.index, {'filter_type': 'films'}, name='films'),
    url(r'^series/$', views.index, {'filter_type': 'series'}, name='series'),

    # Production
    url(r'^production/(?P<slug>[\w-]+)/$', views.production, name='production'),
    url(r'^production/(?P<slug>[\w-]+)/scene/(?P<scene_id>\d+)/locator/$', views.locator, name='locator'),

'''

norloc/common/models.py
# -*- coding: utf-8 -*-

# Imports
from django.db import models
from urllib.parse import urlparse


# Model: Reference
class Reference(models.Model):
    # Fields
    production = models.ForeignKey('productions.Production', 
        null=True, blank=True, on_delete=models.CASCADE
    )
    location = models.ForeignKey('locations.Location', 
        null=True, blank=True, on_delete=models.CASCADE
    )

    title = models.CharField(max_length=100)
    quote = models.TextField(max_length=350, blank=True)
    date = models.DateField('Published')
    source = models.URLField(max_length=200)


    # Metadata
    class Meta:
        ordering = ['-date']


    # Properties
    @property
    def display_url(self):
        return urlparse(self.source).hostname

norloc/locations/models.py
# -*- coding: utf-8 -*-

# Imports
from django.db import models
from django.db.models import Count
from autoslug import AutoSlugField
from jsonfield import JSONField
from urllib.parse import urlparse
from uuid_upload_path import upload_to_factory


# # QuerySet: Locations
# class LocationsQuerySet(models.QuerySet):
#     def has_scene(self):
#         # print self.
#         # print self.aggregate(Count('productions.Scene'))
#         # return self.annotate(scene_count=Count('productions.Scene')).filter(scene_count__isnull=False)
#         # print [l for l in self.all() if l.scene_set.count() not 0]

#         return self.all()


# Upload factories
MIGRATE = False
upload_to_photos = upload_to_factory('locations') if not MIGRATE else 'locations'


NO_COUNTIES = (
    ('akershus', 'Akershus'), ('austagder', 'Aust-Agder'), ('buskerud', 'Buskerud'), 
    ('finnmark', 'Finnmark'), ('hedmark', 'Hedmark'), ('hordaland', 'Hordaland'), 
    ('jan-mayen', 'Jan Mayen'), ('more-og-romsdal', 'Møre og Romsdal'), 
    ('nordtrondelag', 'Nord-Trøndelag'), ('nordland', 'Nordland'), ('oppland', 'Oppland'), 
    ('oslo', 'Oslo'), ('rogaland', 'Rogaland'), ('sogn-og-fjordane', 'Sogn og Fjordane'), 
    ('svalbard', 'Svalbard'), ('sortrondelag', 'Sør-Trøndelag'), ('telemark', 'Telemark'), 
    ('troms', 'Troms'), ('vestagder', 'Vest-Agder'), ('vestfold', 'Vestfold'), 
    ('ostfold', 'Østfold')
)

LOCATION_TYPES = (
    ('park', 'Park'), ('skole', 'Skole'), 
    ('gate', 'Gate'), 
)


# Model: Location
class Location(models.Model):
    # Fields
    address = models.CharField(max_length=150)
    place = models.CharField(max_length=30)
    county = models.CharField(max_length=20, choices=NO_COUNTIES)
    description = models.TextField(max_length=800, blank=True)
    description_credit = models.CharField(max_length=50, blank=True)
    location_type = models.CharField(max_length=30, choices=LOCATION_TYPES, blank=True)
    bounds = JSONField(blank=True, null=True)
    bounds_locked = models.BooleanField(default=False)

    place_slug = AutoSlugField(**{
        'populate_from': 'place', 
        # 'unique_with': ('county',), 
        'unique': False,
        'editable': True,
        'always_update': True,
        'null': True,
    })
    slug = AutoSlugField(**{
        'populate_from': 'address', 
        'unique_with': ('county', 'place_slug'), 
        'editable': True
    })

    # Manager
    # locations = LocationsQuerySet.as_manager()

    # Metadata
    class Meta:
        ordering = ['address']


    # Properties
    @property
    def full_address(self):
        return ', '.join([self.address, self.place, self.get_county_display()])

    # @property
    # def production_count(self):
    #     return self.scene_set.count()

    @property
    def has_bounds(self):
        return True if self.bounds else False
    

    @property
    def photo(self):
        photo = self.photo_set.first()
        return photo if photo and photo.photo else None
    
    
    # Representation
    def __unicode__(self):
        return self.address


# Model: Photo
class Photo(models.Model):
    # Fields
    location = models.ForeignKey('Location', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=upload_to_photos)
    title = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField(blank=True, null=True)
    credit = models.CharField(max_length=50)
    source = models.URLField(max_length=200, blank=True, null=True)
    license = models.CharField(max_length=50, blank=True)

    # Properties
    @property
    def caption(self):
        return '%s%s [%s%s%s]' % (
            self.title,
            ' (%s)' % (self.year) if self.year else '',
            self.credit,
            ' - %s' % (urlparse(self.source).hostname.replace('www.', '')) if self.source else '',
            ' - %s' % (self.license) if self.license else ''
        )

    # Representation
    def __unicode__(self):
        return self.title

norloc/locations/forms.py
# -*- coding: utf-8 -*-

# Imports
from django import forms

from django.contrib.staticfiles.templatetags.staticfiles import static

from .models import Location



# ModelForm: Location
class LocationForm(forms.ModelForm):
    # Meta
    class Meta:
        model = Location

        fields = [
            'address', 'place', 'county', 
            'description', 'description_credit',
            'location_type',
        ]

        # widgets = {
        #     'name': forms.TextInput({'placeholder': 'Navn'}),
        #     'bio': forms.Textarea({'placeholder': 'Biografi'}),
        #     'bio_credit': forms.TextInput({'placeholder': 'Kreditering (biografi)'}),
        #     'imdb_id': forms.TextInput({'placeholder': 'IMDb ID'}),
        #     'tmdb_id': forms.TextInput({'placeholder': 'TMDb ID'}),
        # }

norloc/locations/views.py
# -*- coding: utf-8 -*-

# Imports
from __future__ import unicode_literals

import json
import logging

from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.urls import reverse
from django.db.models import Count

from common.views import error, not_found
from .models import Location, NO_COUNTIES, LOCATION_TYPES
from .forms import LocationForm


# Logger
logger = logging.getLogger('norloc')


# View/JSON: Locations
def locations(request, county=None, place=None, json=False):
    # Filter
    locations = Location.objects
    
    if county:
        locations = locations.filter(county=county)

    if place:
        locations = locations.filter(place_slug=place)

    locations = locations.all().annotate(production_count=Count('scene__production', distinct=True))

    # elif filter in ['film', 'tv']:
    #     # Filter by type
    #     productions = Production.objects.filter(type={
    #         'film': 'film',
    #         'tv': 'show',
    #     }.get(filter)).order_by('-release')

    # else:
    #     # Invalid filter
    #     return not_found(request)


    # Locations in JSON format
    if json:
        # Return JSON
        include_bounds = request.GET.get('bounds', '').lower() == 'true'

        return JsonResponse({'locations': [{
            'pk': location.pk,
            'full_address': location.full_address,
            'bounds': location.bounds if location.bounds else []
        } for location in locations]})

    # Render template
    return render(request, 'locations.html', {
        # 'filter': filter,
        'counties': NO_COUNTIES,
        'location_types': LOCATION_TYPES,
        'locations': locations
    })


# View: Location
def location(request, county, place, slug):
    # Location
    location = get_object_or_404(Location, county=county, place_slug=place, slug=slug)
    edit_request = bool(request.GET.get('edit', False))
    edit_mode = edit_request and request.user.is_authenticated()
    form = None

    # Edit location (GET)
    if request.method == 'GET' and edit_mode:
        # Form
        form = LocationForm(instance=location)

    # Update location (POST)
    if request.method == 'POST' and edit_mode:
        form = LocationForm(instance=location, data=request.POST)#, files=request.FILES)
        
        logger.info('Checking if form is valid')
        
        if form.is_valid():
            # Save
            logger.info('Form valid, saving posted data')
            form.save()

            # Redirect
            return redirect(reverse('location', args=[form.instance.county, form.instance.place_slug, form.instance.slug]) + '?edit=true')

        else:
            logger.error('Form invalid')
            logger.debug(dict(form.errors.items()))

    # Render template
    logger.info('Rendering location (%s), slug=%s, edit_mode=%r (requested=%r, auth=%r)' % (
        request.method, location.slug, edit_mode, edit_request, request.user.is_authenticated
    ))

    return render(request, 'location.html', {
        'edit_mode': edit_mode,
        'form': form if edit_mode else None,
        'location': location
    })


# JSON: Location details
def location_details(request, lpk):
    # Location
    location = get_object_or_404(Location, pk=lpk)
    
    productions = {}

    for scene in location.scene_set.all().order_by('production__release'):
        if scene.production.pk not in productions:
            productions[scene.production.pk] = {
                'pk': scene.production.pk,
                'title': scene.production.title_with_year,
                'poster': scene.production.poster.url if scene.production.poster else None,
                'directors': [p.name for p in scene.production.directors.all()],
                'url': reverse('production', args=[scene.production.type, scene.production.slug]),
                'scenes': []
            }

        productions[scene.production.pk]['scenes'].append({
            'pk': scene.pk,
            'description': scene.description,
            'shot_count': scene.shot_set.count(),
            'uncertain': scene.uncertain,
            'shots': [{
                'image': s.image.url,
                'timecode': s.timecode,
                'double': s.double,
            } for s in scene.shot_set.order_by('timecode', 'pk')]
        })

    # Return JSON
    return JsonResponse({
        'pk': location.pk,
        'url': reverse('location', args=[location.county, location.place_slug, location.slug]),
        'address': location.address,
        'place': location.place,
        'county': location.get_county_display(),
        'description': location.description,
        'photo': location.photo.photo.url if location.photo else None,
        'productions': [p for p in productions.values()],
    })


# JSON: Productions (by location)
def productions(request, lpk):
    # Production
    location = get_object_or_404(Location, pk=lpk)

    # Find all production for given location
    productions = {}

    for scene in location.scene_set.all():
        if scene.production.pk not in productions:
            productions[scene.production.pk] = {
                'title': scene.production.title_with_year,
                'release': scene.production.release,
                'directors': [p.name for p in scene.production.directors.all()],
                'summary': scene.production.summary,
                'summary_credit': scene.production.summary_credit,
                'url': reverse('production', args=[scene.production.type, scene.production.slug]),
                'uncertain': False,
                'poster': scene.production.poster.url if scene.production.poster else None,
                'scenes': []
            }

        productions[scene.production.pk]['uncertain'] = scene.uncertain

        productions[scene.production.pk]['scenes'].append({
            'pk': scene.pk,
            'description': scene.description,
            'shot_count': scene.shot_set.count(),
            'uncertain': scene.uncertain,
            'shots': [{
                'image': s.image.url,
                'timecode': s.timecode,
                'double': s.double,
            } for s in scene.shot_set.order_by('timecode', 'pk')]
        })

    # Return JSON
    return JsonResponse(productions)


# JSON: Update location bounds
@login_required
@require_POST
def update_location_bounds(request, lpk):
    # Location
    location = get_object_or_404(Location, pk=lpk)

    # print '~'*50
    # print location.bounds
    # print location.bounds_locked
    # print '~'*50

    if not request.is_ajax():
        return JsonResponse({'success': False})

    try:
        # Parse data
        bounds = json.loads(request.body)
            
        # Update location bounds
        location.bounds = bounds
        location.save()

    except:
        raise
        return JsonResponse({'success': False})

    # Return JSON
    return JsonResponse({'success': True})

norloc/templates/base_full.html
{% extends "base.html" %}

{% block document %}
 {% block content %}{% endblock %}
{% endblock %}

norloc/templates/error.html
{% extends "base_full.html" %}

{% block view %}error{% endblock %}

{% block navigation %}
 Feil ({{ status_code }})
{% endblock %}


{# Content #}
{% block content-class %}full{% endblock %}
{% block content %}
 <div class="cover-image">
  <img src="/media/shots/uQhBjkogTs-RfVZjXICtHg.jpg">
  <div class="heading">
   <h1>{% if title %}{{ title }}{% else %}Feil{% endif %} <span class="code">&mdash; {{ status_code }}</span></h1>
   <h2>{% if message %}{{ message }}{% else %}Du venner deg til det.{% endif %}</h2>
  </div>
  <div class="caption">
   <h1><a href="{% url 'production' 'film' 'den-brysomme-mannen' %}">Den brysomme mannen</a> <span class="year">(2006)</span></h1>
   <h2>Nydalen stasjon, Nydalen, Oslo</h2>
 </div>
</div>
{% endblock %}

norloc/templates/grid_item_location.html
<div class="grid-item location {% if location.production_count == 0 %}faded{% endif %}" data-href="{% url 'location' location.county location.place_slug location.slug %}" title="{{ location.full_address }}">
 <div class="cover" style="{% if location.photo %}background-image: url('{{ location.photo.photo.url }}');{% endif %}">
 </div>
 <div class="details">
  <h1>{{ location.address }}</h1>
  <h2>{{ location.place }}, {{ location.get_county_display }}</h2>
  <div class="meta">
   <span class="tag" title="Produksjoner"><i class="zmdi zmdi-videocam"></i><span>{{ location.production_count }} produksjon{{ location.production_count|pluralize:",er" }}</span></span>
  </div>
 </div>
</div>

norloc/templates/grid_item_production.html
<div class="grid-item production {%if production.locations|length == 0 %}faded{%endif%}" data-href="{% url 'production' production.type production.slug %}" title="{{ production.title }} ({{ production.release.year }})">
 {%if production.poster %}
  <img src="{{ production.poster.url }}" alt="{{ production.title }} ({{ production.release.year }})">
 {%endif%}
</div>

norloc/templates/header_search.html
<h1>{{title}}</h1>

<form name="search">
 <div class="input-icon">
  <input type="text" name="query" placeholder="{{placeholder}}">
  <button type="submit" name="search" title="Søk"><i class="zmdi zmdi-search"></i></button>
 </div>
</form>

norloc/templates/production.html
{% extends "base_page.html" %}

{% load staticfiles %}
{% load markdownify %}

{% block view %}production{% endblock %}
{% block content_pk %}{{ production.pk }}{% endblock %}
{% block title %}{{production.title}} ({{production.release.year}}) | {% endblock %}

{# Navigation #}
{% block navigation %}
 <a href="{% url 'productions' %}">Produksjoner</a> <span class="accent">&raquo;</span> <a href="{% url 'filtered_productions' production.type %}">{{ production.type }}</a> <span class="accent">&raquo;</span> {{production.title}}

 {% if edit_mode %}
  <a href="{%url 'production' production.type production.slug %}" class="right icon" title="Avbryt endringer"><i class="zmdi zmdi-close"></i></a>
  <a href="" class="right icon" title="Lagre endringer"><i class="zmdi zmdi-save"></i></a>
 {% else %}
  {% if user.is_authenticated %}
   <a href="?edit=true" class="right icon" title="Rediger produksjon"><i class="zmdi zmdi-edit"></i></a>
  {% endif %}
 {% endif %}
{% endblock %}


{# Header #}
{% block header %}
 {% if not edit_mode %}
  <!-- Poster -->
  {% if production.poster %}
   <img src="{{production.poster.url}}" class="poster" alt="poster">
  {% endif %}
  <h1>{{production.title}}</h1>
  <h3>{{production.release.year}}</h3>
  <h4>
   {% for director in production.directors.all %}
    <a href="{%url 'person' director.slug %}" title="Regi">{{director.name}}</a>
   {% endfor %}
  </h4>
  <h4>
   {% if production.writers.count > 0 %}
    <i class="zmdi zmdi-edit" title="Manus"></i>
    {% for writer in production.writers.all %}
     <a href="{%url 'person' writer.slug %}" title="Manus">{{writer.name}}</a>
    {% endfor %}
   {% endif %}
   {% if production.photographers.count > 0 %}
    <i class="zmdi zmdi-videocam" title="Foto"></i>
    {% for photographer in production.photographers.all %}
     <a href="{%url 'person' photographer.slug %}" title="Foto">{{photographer.name}}</a>
    {% endfor %}
   {% endif %}
  </h4>

  <p>
   {{production.summary|markdownify}}{% if production.summary_credit %} <span class="source">&mdash; {{production.summary_credit}}</span>{% endif %}
  </p>

  <div class="meta">
   <span class="tag" title="Premiereår"><i class="zmdi zmdi-calendar-alt"></i><span>{{production.release}}</span></span>
   <span class="tag" title="Lengde"><i class="zmdi zmdi-time"></i><span>{{production.runtime}} min.</span></span>
   <span class="tag" title="Opptakssteder"><i class="zmdi zmdi-pin"></i><span>{{production.locations|length}} opptakssteder</span></span>
  </div>
  <div class="meta">
   {% if production.producers.count > 0 %}
    <span class="tag" title="Produksjon"><i class="zmdi zmdi-case"></i>
     {% for company in production.producers.all %}
      {% if company.website %}
       <a href="{{company.website}}" target="_blank">{{company.name}}</a>
      {% else %}
       <span>{{company.name}}</span>
      {% endif %}
     {% endfor %}
    </span>
   {% endif %}
   {% if production.distributors.count > 0 %}
    <span class="tag" title="Distribusjon"><i class="zmdi zmdi-city-alt"></i>
     {% for company in production.distributors.all %}
      {% if company.website %}
       <a href="{{company.website}}" target="_blank">{{company.name}}</a>
      {% else %}
       <span>{{company.name}}</span>
      {% endif %}
     {% endfor %}
    </span>
   {% endif %}
   <span class="tag" title="Ekstern informasjon"><i class="zmdi zmdi-info-outline"></i>
    {% if production.imdb_id %}<a href="https://www.imdb.com/title/{{production.imdb_id}}" title="Internet Movie Database" target="_blank">IMDb</a>{% endif %}
    {% if production.tmdb_id %}<a href="https://www.themoviedb.org/{% if production.type == 'film' %}movie{% else %}tv{% endif %}/{{production.tmdb_id}}" title="The Movie Database" target="_blank">TMDb</a>{% endif %}
    {% if production.nbdb_id %}<a href="https://www.nb.no/filmografi/show?id={{production.nbdb_id}}" title="Norsk filmografi (Nasjonalbiblioteket)" target="_blank">NBdb</a>{% endif %}
   </span>
  </div>
 {% else %}
  <form id="production_form" method="post" enctype="multipart/form-data">
   {{ form.media }}
   {% csrf_token %}

   {{ form.poster }}
   
   {{ form.errors }}

   {{ form.title }}
   {{ form.release }}

   <div class="people">
    {# <label for="directors" title="Regi"><i class="zmdi zmdi-comment-video"></i></label> #}
    {{ form.directors }}
    {# <input name="directors" value="" class="tagify"> #}
    {# <input name="directors" value='[{"pk":2,"image":"/media/people/EQ-CLMddSduZY38Q2i_mqw.jpg","value":"Dag Johan Haugerud"},{"pk":15,"image":null,"value":"Sara Johnsen"}]' class="tagify"> #}
    {# <label for="writers" title="Manus"><i class="zmdi zmdi-edit"></i></label> #}
    {{ form.writers }}
    {# <label for="photographers" title="Foto"><i class="zmdi zmdi-videocam"></i></label> #}
    {{ form.photographers }}
   </div>

   {{ form.summary }}
   {{ form.summary_credit }}
   {{ form.runtime }}

   <div class="companies">
    {{ form.producers }}
    {{ form.distributors }}
   </div>

   <div class="external_ids">
    <div>
     {{ form.imdb_id }}
     {% if production.imdb_id %}
      <a href="https://www.imdb.com/title/{{production.imdb_id}}" target="_blank">Detaljer</a> 
      | <a href="">Oppdater</a>
     {% else %}
      <a href="https://www.imdb.com/" target="_blank">Søk</a>
     {% endif %}
    </div>
    <div>
     {{ form.tmdb_id }}
     {% if production.tmdb_id %}
      <a href="https://www.themoviedb.org/movie/{{production.tmdb_id}}" target="_blank">Detaljer</a> 
      | <a href="">Oppdater</a>
     {% else %}
      <a href="https://www.themoviedb.org/" target="_blank">Søk</a>
     {% endif %}
    </div>
    <div>
     {{ form.nbdb_id }}
     {% if production.nbdb_id %}
      <a href="https://www.nb.no/filmografi/show?id={{production.nbdb_id}}" target="_blank">Detaljer</a> 
      | <a href="">Oppdater</a>
     {% else %}
      <a href="https://www.nb.no/filmografi/" target="_blank">Søk</a>
     {% endif %}
    </div>
   </div>
  </form>
 {% endif %}
{% endblock %}


{# Menu #}
{% block menu %}{# No menu #}{% endblock %}


{# Content #}
{% block content %}
 {% verbatim %}
 <script id="location-template" type="text/x-handlebars-template">
  <div class="scene-block location {{#if uncertain}}uncertain{{/if}}">
   <h2><a href="{{url}}">{{full_address}}</a></h2>

   <div class="scenes">
    {{#each scenes}}
     <div class="scene {{#if uncertain}}uncertain{{/if}}">
      {{#each shots}}
       <div class="shot {{shot_size double ../shot_count}}">
        <a href="{{image}}" data-lightbox="location-{{../../pk}}" data-title="{{../../full_address}}{{#if timecode}} - {{timecode timecode}}{{/if}}">
         <img src="{{image}}" class="shot">
        </a>
        {{#if timecode}}<span class="timecode">{{timecode timecode}}</span>{{/if}}
       </div>
      {{/each}}
      {{#if description}}
       <p>{{description}}</p>
      {{/if}}
     </div>
    {{/each}}
   </div>
   
   <div class="details">
    {{#if uncertain}}
     <p class="accent">En eller flere scener knyttet til denne lokasjonen er usikker, sannsynligvis feil!</p>
    {{/if}}
    {{#if description}}
     <p>{{{description}}}{{#if description_credit}} <span class="source">&mdash; {{description_credit}}</span>{{/if}}</p>
    {{/if}}
    {{#if photos}}
     <div class="gallery">
      {{#each photos}}
       <a href="{{photo}}" data-lightbox="location-{{../pk}}" data-title="{{../address}}: {{caption}}">
        <div class="image" title="{{caption}}" style="background-image: url('{{photo}}');"></div>
       </a>
      {{/each}}
     </div>
    {{/if}}
   </div>
   
  </div>
 </script>
 {% endverbatim %}
 
 {% if edit_mode %}
  {% verbatim %}
   <script id="tag-template" type="text/x-handlebars-template">
    <div class="tag-content">
     {{#if image}}
      <img src="{{image}}">
     {{/if}}
     <span>{{value}}</span>
    </div>
   </script>
  {% endverbatim %}
 {% endif %}

 {% if production.reference_set.count > 0 %}
  <div id="references">
   {% for reference in production.reference_set.all %}
    <div class="reference">
     <h1><a href="{{ reference.source }}" target="_blank">{{ reference.title }}</a></h1>
     <p>
      {{ reference.quote }}<br>
      <span class="source">&mdash; {{ reference.display_url }} ({{ reference.date }})</span>
     </p>
    </div>
   {% endfor %}
  </div>
 {% endif %}

 {% if user.is_authenticated %}
  <!--div class="location double add">
   <i class="zmdi zmdi-plus-circle"></i>Legg til opptakssted
  </div-->
 {% endif %}
{% endblock %}